#  Copyright (c) 2019. Sophos Limited
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

# Generated by Django 2.2.2 on 2019-06-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SHA",
            fields=[
                (
                    "sha256",
                    models.CharField(
                        db_index=True, max_length=64, primary_key=True, serialize=False
                    ),
                ),
                (
                    "reputation_score",
                    models.IntegerField(blank=True, default="NA", null=True),
                ),
                (
                    "detection_name",
                    models.CharField(
                        blank=True, default="NA", max_length=128, null=True
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_lookup", models.DateTimeField(auto_now=True)),
            ],
        )
    ]
